name: Project Linter Check

on:
  push:
    branches:
      - main

jobs:
  run-ESLinter-check-for-project:
    runs-on: ubuntu-latest
    steps:
      - uses: inadadurov/frontend-project-lvl1/.github/workflows/myActions.yml
      - run: make lint