name: Project Linter Check

on:
  push:
    branches:
      - main

jobs:
  run-ESLinter-check-for-project:
    runs-on: ubuntu-latest
    steps:
      - uses: /home/adadurovin/frontend-project-lvl1/.github/myActions.yml
      - run: make lint